CREATE TABLE ALUNO(
	ID_ALUNO    SERIAL          NOT NULL,
	NOME        VARCHAR(255)    NOT NULL,
	MATRICULA   NUMERIC(7)      NOT NULL,
	APROVADO    VARCHAR(1)      NOT NULL,
	CONSTRAINT  PK_ALUNO        PRIMARY KEY(ID_ALUNO), 
	CONSTRAINT  CK_APROVADO     CHECK(APROVADO = 'S' OR APROVADO = 'N') 
);


INSERT INTO ALUNO(NOME, MATRICULA, APROVADO)
VALUES('JOAO', 0000001, 'S');

INSERT INTO ALUNO(NOME, MATRICULA, APROVADO)
VALUES('MARIA', 0000002, 'S');

INSERT INTO ALUNO(NOME, MATRICULA, APROVADO)
VALUES('PEDRO', 0000003, 'N');

INSERT INTO ALUNO(NOME, MATRICULA, APROVADO)
VALUES('LUCAS', 0000004, 'N');

INSERT INTO ALUNO(NOME, MATRICULA, APROVADO)
VALUES('LUCIA', 0000005, 'S');

INSERT INTO ALUNO(NOME, MATRICULA, APROVADO)
VALUES('INGRID', 0000006, 'S');